begin;
select plan(18);
select has_table('public','os_installation_teams','installation teams exists');
select has_table('public','os_installation_team_members','team members exists');
select has_table('public','os_installations','installations exists');
select has_table('public','os_deliveries','deliveries exists');
select is((select relrowsecurity from pg_class where oid='public.os_installation_teams'::regclass),true,'teams RLS enabled');
select is((select relrowsecurity from pg_class where oid='public.os_installation_team_members'::regclass),true,'members RLS enabled');
select is((select relrowsecurity from pg_class where oid='public.os_installations'::regclass),true,'installations RLS enabled');
select is((select relrowsecurity from pg_class where oid='public.os_deliveries'::regclass),true,'deliveries RLS enabled');
select has_function('public','hub_os_create_installation_team_secure','create team RPC exists');
select has_function('public','hub_os_schedule_installation_secure','schedule installation RPC exists');
select has_function('public','hub_os_reschedule_installation_secure','reschedule installation RPC exists');
select has_function('public','hub_os_cancel_installation_secure','cancel installation RPC exists');
select has_function('public','hub_os_start_installation_secure','start installation RPC exists');
select has_function('public','hub_os_complete_installation_secure','complete installation RPC exists');
select has_function('public','hub_os_schedule_delivery_secure','schedule delivery RPC exists');
select has_function('public','hub_os_start_delivery_secure','start delivery RPC exists');
select has_function('public','hub_os_complete_delivery_secure','complete delivery RPC exists');
select has_function('public','hub_os_cancel_delivery_secure','cancel delivery RPC exists');
select * from finish(); rollback;
