export const PRICING_ERROR_CODES = [
  "INVALID_PRICING_POLICY",
  "INVALID_PRICING_POLICY_VERSION",
  "INVALID_PRICING_RATE",
  "INVALID_PRICING_POLICY_TRANSITION",
  "PRICING_POLICY_VERSION_NOT_EDITABLE",
  "PRICING_POLICY_VERSION_NOT_PUBLISHED",
  "INVALID_PRICING_DEFINITION",
  "INVALID_PRICING_COST_BASIS",
  "INVALID_PRICING_MARKUP",
  "UNSUPPORTED_PRICING_SCHEMA_VERSION",
  "UNSUPPORTED_COSTING_AGGREGATION_VERSION",
  "PRICING_POLICY_NOT_ACTIVE",
  "PRICING_POLICY_VERSION_MISMATCH",
  "DUPLICATE_PRICING_CHARGE",
  "INVALID_PRICING_DENOMINATOR",
  "PRICING_NUMERIC_LIMIT_EXCEEDED",
  "INVALID_PRICING_ENGINE_RESULT",
  "INVALID_COMMERCIAL_PRICING_INPUT",
  "INVALID_COMMERCIAL_PRICING_RESULT",
] as const;
export type PricingErrorCode = (typeof PRICING_ERROR_CODES)[number];
export class PricingDomainError extends Error {
  constructor(
    readonly code: PricingErrorCode,
    message: string,
    readonly details?: Readonly<Record<string, unknown>>
  ) {
    super(message);
    this.name = "PricingDomainError";
  }
}
