import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ from: vi.fn() }));
vi.mock("@/lib/supabase", () => ({ supabase: { from: mocks.from, auth: { getUser: vi.fn() }, rpc: vi.fn() } }));
import { completeOrderDeadline, removeOrderAssignee, removeOrderDeadline, removeOrderItem, reopenOrderDeadline, setOrderAssignee } from "./orderDetailRepository";
const orderId = "11111111-1111-4111-8111-111111111111"; const rowId = "22222222-2222-4222-8222-222222222222";
describe("order detail mutations", () => {
  beforeEach(() => mocks.from.mockReset());
  it("sets and removes an assignee without sentinel UUIDs", async () => { const single = vi.fn().mockResolvedValue({ data: { id: rowId }, error: null }); const select = vi.fn(() => ({ single })); const upsert = vi.fn(() => ({ select })); const eqScope = vi.fn().mockResolvedValue({ error: null }); const eqOrder = vi.fn(() => ({ eq: eqScope })); const del = vi.fn(() => ({ eq: eqOrder })); mocks.from.mockReturnValueOnce({ upsert }); await setOrderAssignee(orderId, "ART", rowId); expect(upsert).toHaveBeenCalledWith(expect.objectContaining({ user_id: rowId }), expect.anything()); mocks.from.mockReturnValueOnce({ delete: del }); await removeOrderAssignee(orderId, "ART"); expect(eqScope).toHaveBeenCalledWith("scope", "ART"); });
  it("completes, reopens and removes deadlines", async () => { const single = vi.fn().mockResolvedValue({ data: {}, error: null }); const select = vi.fn(() => ({ single })); const eqScope = vi.fn(() => ({ select })); const eqOrder = vi.fn(() => ({ eq: eqScope })); const update = vi.fn(() => ({ eq: eqOrder })); mocks.from.mockReturnValueOnce({ update }); await completeOrderDeadline(orderId, "PRODUCTION"); expect(update.mock.calls[0][0].completed_at).toEqual(expect.any(String)); mocks.from.mockReturnValueOnce({ update }); await reopenOrderDeadline(orderId, "PRODUCTION"); expect(update).toHaveBeenLastCalledWith({ completed_at: null }); const removeScope = vi.fn().mockResolvedValue({ error: null }); mocks.from.mockReturnValueOnce({ delete: () => ({ eq: () => ({ eq: removeScope }) }) }); await removeOrderDeadline(orderId, "PRODUCTION"); expect(removeScope).toHaveBeenCalledWith("scope", "PRODUCTION"); });
  it("soft deletes items", async () => { const eq = vi.fn().mockResolvedValue({ error: null }); const update = vi.fn(() => ({ eq })); mocks.from.mockReturnValue({ update }); await removeOrderItem(rowId); expect(update.mock.calls[0][0].deleted_at).toEqual(expect.any(String)); expect(eq).toHaveBeenCalledWith("id", rowId); });
});
