export const COSTING_ERROR_CODES = [
  "NEGATIVE_COST_RATE",
  "INVALID_COST_INTERVAL",
  "COST_RATE_RESOURCE_MISMATCH",
  "COST_RATE_UNIT_MISMATCH",
  "COST_RATE_OVERLAP",
  "MISSING_COST_RATE",
  "AMBIGUOUS_COST_RATE",
  "COST_RESOURCE_NOT_ACTIVE",
  "INVALID_COST_QUANTITY_UNIT",
  "INCOMPATIBLE_COST_UNIT",
  "PRODUCT_VERSION_NOT_PUBLISHED",
  "INVALID_PRODUCT_VERSION_DEFINITION",
  "INVALID_COMMERCIAL_QUANTITY",
  "UNKNOWN_TECHNICAL_INPUT",
  "MISSING_TECHNICAL_INPUT",
  "INVALID_TECHNICAL_INPUT",
  "TECHNICAL_INPUT_OUT_OF_RANGE",
  "INVALID_COMPONENT_CONDITION_RESULT",
  "INVALID_COMPONENT_QUANTITY_RESULT",
  "NEGATIVE_COMPONENT_QUANTITY",
  "COST_RESOURCE_NOT_FOUND",
  "DUPLICATE_COST_RESOURCE",
  "COST_RESOURCE_REFERENCE_MISMATCH",
  "COSTING_AGGREGATION_INCONSISTENT",
] as const;

export type CostingErrorCode = (typeof COSTING_ERROR_CODES)[number];

export class CostingDomainError extends Error {
  constructor(
    public readonly code: CostingErrorCode,
    message: string,
    public readonly details?: Readonly<Record<string, unknown>>
  ) {
    super(message);
    this.name = "CostingDomainError";
  }
}
