import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import type { OsOrder } from "@/features/hubos/types";
export type OrderEditInput = Pick<OsOrder, "title" | "description" | "delivery_date" | "logistic_type" | "address" | "art_direction_tag">;
export function OrderEditDialog({ order, open, onOpenChange, onSave }: { order: OsOrder; open: boolean; onOpenChange: (open: boolean) => void; onSave: (input: OrderEditInput) => Promise<void> }) {
  const [value, setValue] = useState<OrderEditInput>({ title: order.title, description: order.description, delivery_date: order.delivery_date, logistic_type: order.logistic_type, address: order.address, art_direction_tag: order.art_direction_tag });
  const [saving, setSaving] = useState(false);
  useEffect(() => setValue({ title: order.title, description: order.description, delivery_date: order.delivery_date, logistic_type: order.logistic_type, address: order.address, art_direction_tag: order.art_direction_tag }), [order]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>Editar dados operacionais</DialogTitle></DialogHeader><div className="grid gap-4"><div><Label htmlFor="order-title">Título</Label><Input id="order-title" value={value.title ?? ""} onChange={e => setValue(v => ({ ...v, title: e.target.value || null }))} /></div><div><Label htmlFor="order-description">Descrição</Label><Textarea id="order-description" value={value.description ?? ""} onChange={e => setValue(v => ({ ...v, description: e.target.value || null }))} /></div><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="order-deadline">Prazo final</Label><Input id="order-deadline" type="date" value={value.delivery_date ?? ""} onChange={e => setValue(v => ({ ...v, delivery_date: e.target.value || null }))} /></div><div><Label>Logística</Label><Select value={value.logistic_type} onValueChange={logistic_type => setValue(v => ({ ...v, logistic_type: logistic_type as OsOrder["logistic_type"] }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="retirada">Retirada</SelectItem><SelectItem value="entrega">Entrega</SelectItem><SelectItem value="instalacao">Instalação</SelectItem></SelectContent></Select></div></div><div><Label htmlFor="order-address">Endereço</Label><Input id="order-address" value={value.address ?? ""} onChange={e => setValue(v => ({ ...v, address: e.target.value || null }))} /></div><div><Label>Prioridade</Label><Select value={value.art_direction_tag === "URGENTE" ? "URGENTE" : "NORMAL"} onValueChange={priority => setValue(v => ({ ...v, art_direction_tag: priority === "URGENTE" ? "URGENTE" : null }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="NORMAL">Normal</SelectItem><SelectItem value="URGENTE">Urgente</SelectItem></SelectContent></Select></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button disabled={saving} onClick={async () => { setSaving(true); try { await onSave(value); onOpenChange(false); } finally { setSaving(false); } }}>{saving ? "Salvando…" : "Salvar"}</Button></DialogFooter></DialogContent></Dialog>;
}

