import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import type { OrderItem } from "../types/orderDetail";
import { OrderItemDialog, type OrderItemInput } from "./OrderItemDialog";
export type ItemDraft = OrderItemInput;
const statusLabel = { PENDING: "Pendente", IN_PROGRESS: "Em andamento", READY: "Pronto", CANCELLED: "Cancelado" };
export function OrderItemsTab({ items, loading, error, canEdit, onCreate, onUpdate, onRemove, onMove }: { items: OrderItem[]; loading: boolean; error: string | null; canEdit: boolean; onCreate: (draft: ItemDraft) => Promise<void>; onUpdate: (id: string, input: Partial<OrderItem>) => Promise<void>; onRemove: (id: string) => Promise<void>; onMove: (index: number, direction: -1 | 1) => Promise<void> }) {
  const [dialog, setDialog] = useState<"create" | "edit" | null>(null); const [selected, setSelected] = useState<OrderItem | null>(null); const [removing, setRemoving] = useState<OrderItem | null>(null);
  if (loading) return <p className="text-sm text-muted-foreground">Carregando itens…</p>; if (error) return <p className="text-sm text-destructive">{error}</p>;
  return <div className="space-y-4">{canEdit && <div className="flex justify-end"><Button onClick={() => { setSelected(null); setDialog("create"); }}>Adicionar item</Button></div>}
    {!items.length ? <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">Nenhum item estruturado cadastrado.</p> : <div className="space-y-2">{items.map((item, index) => <Card key={item.id}><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><span className="text-sm font-bold text-muted-foreground">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0 flex-1"><p className="font-medium">{item.name}</p>{item.description && <p className="line-clamp-1 text-sm text-muted-foreground">{item.description}</p>}<p className="text-sm text-muted-foreground">{item.quantity} {item.unit}{(item.width_cm || item.height_cm) && ` · ${item.width_cm ?? "—"} × ${item.height_cm ?? "—"} cm`} · {statusLabel[item.status]}</p></div>{canEdit && <div className="flex flex-wrap items-center gap-1"><Button variant="outline" size="sm" onClick={() => { setSelected(item); setDialog("edit"); }}>Editar</Button><Button variant="ghost" size="sm" disabled={index === 0} onClick={() => onMove(index, -1)}>↑</Button><Button variant="ghost" size="sm" disabled={index === items.length - 1} onClick={() => onMove(index, 1)}>↓</Button><Button variant="ghost" size="sm" onClick={() => setRemoving(item)}>Remover</Button></div>}</CardContent></Card>)}</div>}
    <OrderItemDialog open={dialog !== null} onOpenChange={open => !open && setDialog(null)} item={selected} sortOrder={items.length} onSave={value => selected ? onUpdate(selected.id, value) : onCreate(value)} />
    <AlertDialog open={Boolean(removing)} onOpenChange={open => !open && setRemoving(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remover item?</AlertDialogTitle><AlertDialogDescription>Deseja remover o item “{removing?.name}”? Esta exclusão será registrada no histórico.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={() => removing && onRemove(removing.id)}>Remover</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
