import { useState } from "react";
import { MoreHorizontal } from "lucide-react";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"; import { Input } from "@/components/ui/input";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { getDeadlineState } from "../services/orderDeadlines"; import type { DeadlineScope, OrderDeadline } from "../types/orderDetail";
const scopes: { value: DeadlineScope; label: string }[] = [{ value: "ART", label: "Arte" }, { value: "APPROVAL", label: "Aprovação" }, { value: "PRODUCTION", label: "Produção" }, { value: "FINISHING", label: "Acabamento" }, { value: "INSTALLATION", label: "Instalação" }];
const stateLabel = { NORMAL: "Normal", TODAY: "Vence hoje", OVERDUE: "Atrasado", COMPLETED: "Concluído" };
const date = (value: string | null) => value ? value.split("-").reverse().join("/") : "Não definido";
export function OrderDeadlinesCard({ deadlines, finalDeadline, canEdit, onChange, onComplete, onReopen, onRemove }: { deadlines: OrderDeadline[]; finalDeadline: string | null; canEdit: boolean; onChange: (scope: DeadlineScope, date: string) => void; onComplete: (scope: DeadlineScope) => void; onReopen: (scope: DeadlineScope) => void; onRemove: (scope: DeadlineScope) => void }) {
  const [editing, setEditing] = useState<DeadlineScope | null>(null); const [removing, setRemoving] = useState<DeadlineScope | null>(null);
  return <Card><CardHeader><CardTitle>Prazos</CardTitle></CardHeader><CardContent className="space-y-3">{scopes.map(scope => { const deadline = deadlines.find(item => item.scope === scope.value); const state = deadline && getDeadlineState(deadline); return <div key={scope.value} className="grid grid-cols-[1fr_auto] gap-2 sm:grid-cols-[120px_1fr_auto_auto] sm:items-center"><span className="text-sm text-muted-foreground">{scope.label}</span><div>{canEdit && (editing === scope.value || !deadline) ? <Input className="max-w-48" type="date" value={deadline?.due_date ?? ""} onChange={event => { if (event.target.value) { onChange(scope.value, event.target.value); setEditing(null); } }} /> : <span className="text-sm font-medium">{date(deadline?.due_date ?? null)}</span>}</div>{state && <Badge variant={state === "OVERDUE" ? "destructive" : "secondary"}>{stateLabel[state]}</Badge>}{canEdit && deadline && <DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" aria-label={`Ações do prazo de ${scope.label}`}><MoreHorizontal className="h-4 w-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => setEditing(scope.value)}>Alterar</DropdownMenuItem>{deadline.completed_at ? <DropdownMenuItem onClick={() => onReopen(scope.value)}>Reabrir</DropdownMenuItem> : <DropdownMenuItem onClick={() => onComplete(scope.value)}>Concluir</DropdownMenuItem>}<DropdownMenuItem className="text-destructive" onClick={() => setRemoving(scope.value)}>Remover prazo</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}</div>; })}<div className="grid border-t pt-3 sm:grid-cols-[120px_1fr]"><span className="text-sm text-muted-foreground">Prazo final</span><strong>{date(finalDeadline)}</strong></div>
  <AlertDialog open={Boolean(removing)} onOpenChange={open => !open && setRemoving(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remover prazo?</AlertDialogTitle><AlertDialogDescription>O prazo desta etapa será removido. A ação ficará registrada no histórico.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={() => { if (removing) onRemove(removing); setRemoving(null); }}>Remover</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></CardContent></Card>;
}
