-- Evolução OS 2.0 — Fase 4: logistics starts only after Material Pronto.
create table if not exists public.os_installation_teams (
 id uuid primary key default gen_random_uuid(), name text not null check(length(trim(name))>0), active boolean not null default true,
 default_vehicle_label text, notes text, created_by uuid references public.profiles(id), updated_by uuid references public.profiles(id),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.os_installation_team_members (
 team_id uuid not null references public.os_installation_teams(id) on delete cascade, user_id uuid not null references public.profiles(id),
 is_lead boolean not null default false, created_at timestamptz not null default now(), created_by uuid references public.profiles(id), primary key(team_id,user_id)
);
create unique index if not exists os_installation_team_one_lead_idx on public.os_installation_team_members(team_id) where is_lead;
create index if not exists os_installation_team_members_user_idx on public.os_installation_team_members(user_id);
create table if not exists public.os_installations (
 id uuid primary key default gen_random_uuid(), os_id uuid not null references public.os_orders(id), team_id uuid references public.os_installation_teams(id), responsible_id uuid references public.profiles(id),
 status text not null default 'SCHEDULED' check(status in ('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED')),
 scheduled_start timestamptz not null, scheduled_end timestamptz, estimated_duration_minutes integer check(estimated_duration_minutes is null or estimated_duration_minutes>0),
 vehicle_label text, address_snapshot text not null, address_lat double precision, address_lng double precision, notes text, started_at timestamptz, completed_at timestamptz,
 cancelled_at timestamptz, cancelled_reason text, created_by uuid references public.profiles(id), updated_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 check(scheduled_end is null or scheduled_end>scheduled_start), check(status<>'CANCELLED' or (cancelled_at is not null and length(trim(cancelled_reason))>0)), check(status<>'COMPLETED' or completed_at is not null)
);
create unique index if not exists os_installations_one_active_per_os_idx on public.os_installations(os_id) where status in ('SCHEDULED','IN_PROGRESS');
create index if not exists os_installations_status_start_idx on public.os_installations(status,scheduled_start);
create index if not exists os_installations_team_start_idx on public.os_installations(team_id,scheduled_start) where status in ('SCHEDULED','IN_PROGRESS');
create index if not exists os_installations_responsible_idx on public.os_installations(responsible_id);
create table if not exists public.os_deliveries (
 id uuid primary key default gen_random_uuid(), os_id uuid not null references public.os_orders(id), mode text not null check(mode in ('OWN_DELIVERY','CARRIER')),
 status text not null default 'SCHEDULED' check(status in ('SCHEDULED','IN_TRANSIT','COMPLETED','CANCELLED')), scheduled_at timestamptz,
 assigned_to uuid references public.profiles(id), vehicle_label text, carrier_name text, tracking_code text, recipient_name text, notes text, completed_at timestamptz,
 cancelled_at timestamptz, cancelled_reason text, created_by uuid references public.profiles(id), updated_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 check(status<>'CANCELLED' or (cancelled_at is not null and length(trim(cancelled_reason))>0)), check(status<>'COMPLETED' or completed_at is not null)
);
create unique index if not exists os_deliveries_one_active_per_os_idx on public.os_deliveries(os_id) where status in ('SCHEDULED','IN_TRANSIT');
create index if not exists os_deliveries_status_scheduled_idx on public.os_deliveries(status,scheduled_at);
create index if not exists os_deliveries_assigned_idx on public.os_deliveries(assigned_to);

alter table public.os_installation_teams enable row level security; alter table public.os_installation_team_members enable row level security; alter table public.os_installations enable row level security; alter table public.os_deliveries enable row level security;
create policy os_installation_teams_select_hub on public.os_installation_teams for select to authenticated using(exists(select 1 from public.user_module_access a where a.user_id=auth.uid() and a.module_key='hub_os'));
create policy os_installation_members_select_hub on public.os_installation_team_members for select to authenticated using(exists(select 1 from public.user_module_access a where a.user_id=auth.uid() and a.module_key='hub_os'));
create policy os_installations_select_hub on public.os_installations for select to authenticated using(exists(select 1 from public.user_module_access a where a.user_id=auth.uid() and a.module_key='hub_os'));
create policy os_deliveries_select_hub on public.os_deliveries for select to authenticated using(exists(select 1 from public.user_module_access a where a.user_id=auth.uid() and a.module_key='hub_os'));

create or replace function public.hub_os_logistics_role() returns text language sql stable security definer set search_path=public as $$ select case when role='admin' then 'gerente' else role end from public.profiles where id=auth.uid() $$;
revoke execute on function public.hub_os_logistics_role() from public,anon,authenticated;
create or replace function public.hub_os_assert_logistics_actor(p_manage text) returns uuid language plpgsql security definer set search_path=public as $$declare u uuid:=auth.uid();r text;begin if u is null then raise exception 'Autenticação obrigatória.' using errcode='42501';end if;select public.hub_os_logistics_role() into r;if not exists(select 1 from public.user_module_access where user_id=u and module_key='hub_os') then raise exception 'Acesso ao Hub OS obrigatório.' using errcode='42501';end if;if p_manage='INSTALLATION' and r<>'gerente' then raise exception 'Somente gerente pode gerenciar instalações.' using errcode='42501';elsif p_manage='DELIVERY' and r not in ('gerente','producao') then raise exception 'Sem permissão para gerenciar entregas.' using errcode='42501';end if;return u;end$$;
revoke execute on function public.hub_os_assert_logistics_actor(text) from public,anon,authenticated;

create or replace function public.hub_os_create_installation_team_secure(p_name text,p_default_vehicle_label text default null,p_notes text default null) returns public.os_installation_teams language plpgsql security definer set search_path=public as $$declare u uuid:=public.hub_os_assert_logistics_actor('INSTALLATION');v public.os_installation_teams;begin insert into public.os_installation_teams(name,default_vehicle_label,notes,created_by,updated_by) values(trim(p_name),nullif(trim(p_default_vehicle_label),''),nullif(trim(p_notes),''),u,u) returning * into v;return v;end$$;
create or replace function public.hub_os_update_installation_team_secure(p_team_id uuid,p_name text,p_active boolean,p_default_vehicle_label text default null,p_notes text default null) returns public.os_installation_teams language plpgsql security definer set search_path=public as $$declare u uuid:=public.hub_os_assert_logistics_actor('INSTALLATION');v public.os_installation_teams;begin update public.os_installation_teams set name=trim(p_name),active=p_active,default_vehicle_label=nullif(trim(p_default_vehicle_label),''),notes=nullif(trim(p_notes),''),updated_by=u,updated_at=now() where id=p_team_id returning * into v;if v.id is null then raise exception 'Equipe não encontrada.';end if;return v;end$$;
create or replace function public.hub_os_set_installation_team_members_secure(p_team_id uuid,p_members jsonb) returns setof public.os_installation_team_members language plpgsql security definer set search_path=public as $$declare u uuid:=public.hub_os_assert_logistics_actor('INSTALLATION');begin if not exists(select 1 from public.os_installation_teams where id=p_team_id) then raise exception 'Equipe não encontrada.';end if;if exists(select 1 from jsonb_to_recordset(coalesce(p_members,'[]')) as x(user_id uuid,is_lead boolean) left join public.profiles p on p.id=x.user_id where p.id is null or (case when p.role='admin' then 'gerente' else p.role end) not in ('instalador','gerente')) then raise exception 'Membro inválido: use instalador ou gerente.';end if;if (select count(*) from jsonb_to_recordset(coalesce(p_members,'[]')) as x(user_id uuid,is_lead boolean) where is_lead)>1 then raise exception 'A equipe pode possuir apenas um líder.';end if;delete from public.os_installation_team_members where team_id=p_team_id;insert into public.os_installation_team_members(team_id,user_id,is_lead,created_by) select p_team_id,x.user_id,coalesce(x.is_lead,false),u from jsonb_to_recordset(coalesce(p_members,'[]')) as x(user_id uuid,is_lead boolean);return query select * from public.os_installation_team_members where team_id=p_team_id;end$$;

create or replace function public.hub_os_schedule_installation_secure(p_os_id uuid,p_scheduled_start timestamptz,p_scheduled_end timestamptz default null,p_team_id uuid default null,p_responsible_id uuid default null,p_estimated_duration_minutes integer default null,p_vehicle_label text default null,p_notes text default null,p_override_conflict boolean default false) returns public.os_installations language plpgsql security definer set search_path=public as $$declare u uuid:=public.hub_os_assert_logistics_actor('INSTALLATION');o public.os_orders;v public.os_installations;v_end timestamptz:=coalesce(p_scheduled_end,p_scheduled_start+make_interval(mins=>coalesce(p_estimated_duration_minutes,120)));begin select * into o from public.os_orders where id=p_os_id for update;if o.id is null or o.archived then raise exception 'OS inexistente ou arquivada.';end if;if o.logistic_type<>'instalacao' then raise exception 'OS não é do tipo instalação.';end if;if o.prod_status not in ('Pronto / Avisar Cliente','Instalação Agendada') then raise exception 'OS deve estar em Material Pronto.';end if;if p_team_id is not null and not exists(select 1 from public.os_installation_teams where id=p_team_id and active) then raise exception 'Equipe inválida ou inativa.';end if;if p_team_id is not null and not p_override_conflict and exists(select 1 from public.os_installations i where i.team_id=p_team_id and i.status in ('SCHEDULED','IN_PROGRESS') and tstzrange(i.scheduled_start,coalesce(i.scheduled_end,i.scheduled_start+make_interval(mins=>coalesce(i.estimated_duration_minutes,120))),'[)')&&tstzrange(p_scheduled_start,v_end,'[)')) then raise exception 'Esta equipe já possui instalação neste horário.';end if;insert into public.os_installations(os_id,team_id,responsible_id,scheduled_start,scheduled_end,estimated_duration_minutes,vehicle_label,address_snapshot,address_lat,address_lng,notes,created_by,updated_by) values(o.id,p_team_id,p_responsible_id,p_scheduled_start,p_scheduled_end,p_estimated_duration_minutes,nullif(trim(p_vehicle_label),''),coalesce(o.address,''),o.address_lat,o.address_lng,nullif(trim(p_notes),''),u,u) returning * into v;update public.os_orders set prod_status='Instalação Agendada',updated_at=now() where id=o.id;insert into public.os_orders_event(os_id,type,payload,created_by) values(o.id,'INSTALLATION_SCHEDULED',jsonb_build_object('installation_id',v.id,'scheduled_start',v.scheduled_start,'team_id',v.team_id),u);return v;end$$;
create or replace function public.hub_os_reschedule_installation_secure(p_installation_id uuid,p_scheduled_start timestamptz,p_scheduled_end timestamptz default null,p_team_id uuid default null,p_responsible_id uuid default null,p_estimated_duration_minutes integer default null,p_vehicle_label text default null,p_notes text default null,p_override_conflict boolean default false) returns public.os_installations language plpgsql security definer set search_path=public as $$declare u uuid:=public.hub_os_assert_logistics_actor('INSTALLATION');v public.os_installations;old public.os_installations;v_end timestamptz:=coalesce(p_scheduled_end,p_scheduled_start+make_interval(mins=>coalesce(p_estimated_duration_minutes,120)));begin select * into old from public.os_installations where id=p_installation_id for update;if old.status<>'SCHEDULED' then raise exception 'Somente instalação agendada pode ser reagendada.';end if;if p_team_id is not null and not p_override_conflict and exists(select 1 from public.os_installations i where i.id<>old.id and i.team_id=p_team_id and i.status in ('SCHEDULED','IN_PROGRESS') and tstzrange(i.scheduled_start,coalesce(i.scheduled_end,i.scheduled_start+make_interval(mins=>coalesce(i.estimated_duration_minutes,120))),'[)')&&tstzrange(p_scheduled_start,v_end,'[)')) then raise exception 'Esta equipe já possui instalação neste horário.';end if;update public.os_installations set scheduled_start=p_scheduled_start,scheduled_end=p_scheduled_end,team_id=p_team_id,responsible_id=p_responsible_id,estimated_duration_minutes=p_estimated_duration_minutes,vehicle_label=nullif(trim(p_vehicle_label),''),notes=nullif(trim(p_notes),''),updated_by=u,updated_at=now() where id=old.id returning * into v;insert into public.os_orders_event(os_id,type,payload,created_by) values(v.os_id,'INSTALLATION_RESCHEDULED',jsonb_build_object('installation_id',v.id,'from',jsonb_build_object('scheduled_start',old.scheduled_start,'scheduled_end',old.scheduled_end,'team_id',old.team_id,'responsible_id',old.responsible_id),'to',jsonb_build_object('scheduled_start',v.scheduled_start,'scheduled_end',v.scheduled_end,'team_id',v.team_id,'responsible_id',v.responsible_id)),u);return v;end$$;
create or replace function public.hub_os_cancel_installation_secure(p_installation_id uuid,p_cancelled_reason text) returns public.os_installations language plpgsql security definer set search_path=public as $$declare u uuid:=public.hub_os_assert_logistics_actor('INSTALLATION');v public.os_installations;begin if length(trim(coalesce(p_cancelled_reason,'')))=0 then raise exception 'Motivo do cancelamento é obrigatório.';end if;select * into v from public.os_installations where id=p_installation_id for update;if v.status not in ('SCHEDULED','IN_PROGRESS') then raise exception 'Instalação não está ativa.';end if;perform 1 from public.os_orders where id=v.os_id for update;update public.os_installations set status='CANCELLED',cancelled_at=now(),cancelled_reason=trim(p_cancelled_reason),updated_by=u,updated_at=now() where id=v.id returning * into v;update public.os_orders set prod_status='Pronto / Avisar Cliente',updated_at=now() where id=v.os_id and not exists(select 1 from public.os_installations where os_id=v.os_id and status in ('SCHEDULED','IN_PROGRESS'));insert into public.os_orders_event(os_id,type,payload,created_by) values(v.os_id,'INSTALLATION_CANCELLED',jsonb_build_object('installation_id',v.id,'reason',v.cancelled_reason),u);return v;end$$;
create or replace function public.hub_os_start_installation_secure(p_installation_id uuid) returns public.os_installations language plpgsql security definer set search_path=public as $$declare u uuid:=auth.uid();r text;v public.os_installations;begin if u is null then raise exception 'Autenticação obrigatória.' using errcode='42501';end if;select * into v from public.os_installations where id=p_installation_id for update;select public.hub_os_logistics_role() into r;if r<>'gerente' and v.responsible_id is distinct from u and not exists(select 1 from public.os_installation_team_members where team_id=v.team_id and user_id=u) then raise exception 'Instalação não atribuída a este usuário.' using errcode='42501';end if;if v.status<>'SCHEDULED' then raise exception 'Instalação não está agendada.';end if;perform 1 from public.os_orders where id=v.os_id for update;update public.os_installations set status='IN_PROGRESS',started_at=now(),updated_by=u,updated_at=now() where id=v.id returning * into v;insert into public.os_orders_event(os_id,type,payload,created_by) values(v.os_id,'INSTALLATION_STARTED',jsonb_build_object('installation_id',v.id),u);return v;end$$;
create or replace function public.hub_os_complete_installation_secure(p_installation_id uuid) returns public.os_installations language plpgsql security definer set search_path=public as $$declare u uuid:=auth.uid();r text;v public.os_installations;begin if u is null then raise exception 'Autenticação obrigatória.' using errcode='42501';end if;select * into v from public.os_installations where id=p_installation_id for update;select public.hub_os_logistics_role() into r;if r<>'gerente' and (v.status<>'IN_PROGRESS' or (v.responsible_id is distinct from u and not exists(select 1 from public.os_installation_team_members where team_id=v.team_id and user_id=u))) then raise exception 'Sem permissão para concluir.' using errcode='42501';end if;if v.status not in ('SCHEDULED','IN_PROGRESS') then raise exception 'Instalação não pode ser concluída.';end if;perform 1 from public.os_orders where id=v.os_id for update;update public.os_installations set status='COMPLETED',started_at=coalesce(started_at,now()),completed_at=now(),updated_by=u,updated_at=now() where id=v.id returning * into v;update public.os_orders set prod_status='Finalizados',updated_at=now() where id=v.os_id;insert into public.os_orders_event(os_id,type,payload,created_by) values(v.os_id,'INSTALLATION_COMPLETED',jsonb_build_object('installation_id',v.id,'direct_completion',v.started_at=v.completed_at),u);return v;end$$;

create or replace function public.hub_os_schedule_delivery_secure(p_os_id uuid,p_mode text,p_scheduled_at timestamptz default null,p_assigned_to uuid default null,p_vehicle_label text default null,p_carrier_name text default null,p_tracking_code text default null,p_notes text default null) returns public.os_deliveries language plpgsql security definer set search_path=public as $$declare u uuid:=public.hub_os_assert_logistics_actor('DELIVERY');o public.os_orders;v public.os_deliveries;begin select * into o from public.os_orders where id=p_os_id for update;if o.id is null or o.archived or o.logistic_type<>'entrega' then raise exception 'OS inexistente, arquivada ou não é entrega.';end if;if o.prod_status not in ('Pronto / Avisar Cliente','Logística (Entrega/Transportadora)') then raise exception 'OS deve estar em Material Pronto.';end if;if p_mode not in ('OWN_DELIVERY','CARRIER') then raise exception 'Modalidade inválida.';end if;insert into public.os_deliveries(os_id,mode,scheduled_at,assigned_to,vehicle_label,carrier_name,tracking_code,notes,created_by,updated_by) values(o.id,p_mode,p_scheduled_at,p_assigned_to,nullif(trim(p_vehicle_label),''),nullif(trim(p_carrier_name),''),nullif(trim(p_tracking_code),''),nullif(trim(p_notes),''),u,u) returning * into v;update public.os_orders set prod_status='Logística (Entrega/Transportadora)',updated_at=now() where id=o.id;insert into public.os_orders_event(os_id,type,payload,created_by) values(o.id,'DELIVERY_SCHEDULED',jsonb_build_object('delivery_id',v.id,'mode',v.mode,'scheduled_at',v.scheduled_at,'carrier_name',v.carrier_name),u);return v;end$$;
create or replace function public.hub_os_start_delivery_secure(p_delivery_id uuid,p_carrier_name text default null,p_tracking_code text default null) returns public.os_deliveries language plpgsql security definer set search_path=public as $$declare u uuid:=public.hub_os_assert_logistics_actor('DELIVERY');v public.os_deliveries;begin select * into v from public.os_deliveries where id=p_delivery_id for update;if v.status<>'SCHEDULED' then raise exception 'Entrega não está agendada.';end if;perform 1 from public.os_orders where id=v.os_id for update;update public.os_deliveries set status='IN_TRANSIT',carrier_name=case when mode='CARRIER' then coalesce(nullif(trim(p_carrier_name),''),carrier_name) else carrier_name end,tracking_code=case when mode='CARRIER' then coalesce(nullif(trim(p_tracking_code),''),tracking_code) else tracking_code end,updated_by=u,updated_at=now() where id=v.id returning * into v;insert into public.os_orders_event(os_id,type,payload,created_by) values(v.os_id,'DELIVERY_STARTED',jsonb_build_object('delivery_id',v.id,'mode',v.mode,'carrier_name',v.carrier_name,'tracking_code',v.tracking_code),u);return v;end$$;
create or replace function public.hub_os_complete_delivery_secure(p_delivery_id uuid,p_recipient_name text default null) returns public.os_deliveries language plpgsql security definer set search_path=public as $$declare u uuid:=public.hub_os_assert_logistics_actor('DELIVERY');v public.os_deliveries;begin select * into v from public.os_deliveries where id=p_delivery_id for update;if v.status not in ('SCHEDULED','IN_TRANSIT') then raise exception 'Entrega não pode ser concluída.';end if;perform 1 from public.os_orders where id=v.os_id for update;update public.os_deliveries set status='COMPLETED',completed_at=now(),recipient_name=nullif(trim(p_recipient_name),''),updated_by=u,updated_at=now() where id=v.id returning * into v;update public.os_orders set prod_status='Finalizados',updated_at=now() where id=v.os_id;insert into public.os_orders_event(os_id,type,payload,created_by) values(v.os_id,'DELIVERY_COMPLETED',jsonb_build_object('delivery_id',v.id,'recipient_name',v.recipient_name),u);return v;end$$;
create or replace function public.hub_os_cancel_delivery_secure(p_delivery_id uuid,p_cancelled_reason text) returns public.os_deliveries language plpgsql security definer set search_path=public as $$declare u uuid:=public.hub_os_assert_logistics_actor('DELIVERY');v public.os_deliveries;begin if length(trim(coalesce(p_cancelled_reason,'')))=0 then raise exception 'Motivo do cancelamento é obrigatório.';end if;select * into v from public.os_deliveries where id=p_delivery_id for update;if v.status not in ('SCHEDULED','IN_TRANSIT') then raise exception 'Entrega não está ativa.';end if;perform 1 from public.os_orders where id=v.os_id for update;update public.os_deliveries set status='CANCELLED',cancelled_at=now(),cancelled_reason=trim(p_cancelled_reason),updated_by=u,updated_at=now() where id=v.id returning * into v;update public.os_orders set prod_status='Pronto / Avisar Cliente',updated_at=now() where id=v.os_id and not exists(select 1 from public.os_deliveries where os_id=v.os_id and status in ('SCHEDULED','IN_TRANSIT'));insert into public.os_orders_event(os_id,type,payload,created_by) values(v.os_id,'DELIVERY_CANCELLED',jsonb_build_object('delivery_id',v.id,'reason',v.cancelled_reason),u);return v;end$$;
-- No direct mutation policies: all writes cross the validated transaction boundary above.
revoke insert,update,delete on public.os_installation_teams,public.os_installation_team_members,public.os_installations,public.os_deliveries from anon,authenticated;
grant select on public.os_installation_teams,public.os_installation_team_members,public.os_installations,public.os_deliveries to authenticated;
do $$declare r record;begin for r in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'hub_os_%_secure' and p.proname in ('hub_os_create_installation_team_secure','hub_os_update_installation_team_secure','hub_os_set_installation_team_members_secure','hub_os_schedule_installation_secure','hub_os_reschedule_installation_secure','hub_os_cancel_installation_secure','hub_os_start_installation_secure','hub_os_complete_installation_secure','hub_os_schedule_delivery_secure','hub_os_start_delivery_secure','hub_os_complete_delivery_secure','hub_os_cancel_delivery_secure') loop execute format('revoke execute on function %s from public, anon',r.sig);execute format('grant execute on function %s to authenticated',r.sig);end loop;end$$;
do $$begin if exists(select 1 from pg_publication where pubname='supabase_realtime') then if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='os_installations') then alter publication supabase_realtime add table public.os_installations;end if;if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='os_installation_teams') then alter publication supabase_realtime add table public.os_installation_teams;end if;if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='os_installation_team_members') then alter publication supabase_realtime add table public.os_installation_team_members;end if;if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='os_deliveries') then alter publication supabase_realtime add table public.os_deliveries;end if;end if;end$$;
